# Generated by Django 3.2 on 2023-03-11 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subscriptions',
            field=models.ManyToManyField(related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
