# Generated by Django 3.2 on 2023-03-14 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20230311_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
